In [50]:
import numpy as np
import pandas as pd
import os
import pickle

## Read Training Data

In [71]:
PICKLE_FILE = "../processed_data/pickle/data.pickle"
df = pickle.load(open(PICKLE_FILE, "rb"))
df.drop(["device_id", "gender", "age", "group", "event_ids", "app_ids", "label_ids"], axis=1, inplace=True)
df.head(n=3)

phone_brand_id  device_model_id  group_id
0               0                1        10
1               0                1        10
2               0                1        10

## Data Analysis

In [67]:
# number of unique device models in data set:
print(df["device_model_id"].unique().size)
# max id
print(df["device_model_id"].max())
# min id
print(df["device_model_id"].min())

unique device model ids: 1438
max id: 1597
min id: 0


Data contains 1438 different device models ranging from 0-1597.

In [68]:
# number of unique phone brands in train set:
print(df["phone_brand_id"].unique().size)
# max id
print(df["phone_brand_id"].max())
# min id
print(df["device_model_id"].min())

120
130
0


Data contains 120 different phone brands ranging from 0-130.